In [132]:
# Initial imports
import os
from pathlib import Path
import pandas as pd
from newsapi import NewsApiClient
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from dotenv import load_dotenv

In [133]:
load_dotenv()

True

In [134]:
nltk.download('vader_lexicon')            # need this for sentiment analyzer further down in code
analyzer = SentimentIntensityAnalyzer()

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\james\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [135]:
# api_key ='c5c492da6d534f529f2d9c386c8f500f'  ##sasha stuff

In [136]:
# api_key = "NEWS_API_KEY"  # me doin stuff

In [137]:
# api_key = os.getenv("QUANDL_API_KEY")    # garence stuff

In [138]:
key = os.getenv("NEWS_API_KEY")   # garence stuff

In [139]:
# Verify variable type

type(key)

str

In [140]:
# Verify Key connectivity

(key)

'c1663debb8fa46dba0048fd4c8d88a49'

In [141]:
newsapi = NewsApiClient(api_key=key)
# newsapi = NewsApiClient(api_key=NEWS_API_KEY)
# newsapi = NewsApiClient(NEWS_API_KEY=api_key)

In [142]:
refinery_headlines = newsapi.get_everything(             # this works
    q="storm" and "refinery outage",
    language="en",
)

print(f"Total articles about refinery headlines: {shooting_headlines['totalResults']}")


refinery_headlines["articles"]

Total articles about refinery headlines: 28

[{'source': {'id': 'reuters', 'name': 'Reuters'},
  'author': None,
  'title': 'California diesel, jet prices rise on Chevron hydrotreater outage -trade - Reuters',
  'description': 'California diesel prices climbed 52.5 cents a gallon this week in the San Francisco Bay market because of a hydrotreater outage at Chevron Corp’s <a href="https://www.reuters.com/companies/CVX.N" target="_blank">(CVX.N)</a> Richmond, California, refinery, sai…',
  'url': 'https://www.reuters.com/business/energy/california-diesel-jet-prices-rise-chevron-hydrotreater-outage-trade-2022-03-25/',
  'urlToImage': 'https://www.reuters.com/resizer/A19XoPsXF1dbZWI2xNRrWmaMdSE=/1200x628/smart/filters:quality(80)/cloudfront-us-east-2.images.arcpublishing.com/reuters/UJ5AOSVIABJLPI3OHMAEC2R5KI.jpg',
  'publishedAt': '2022-03-25T22:22:00Z',
  'content': 'HOUSTON, March 25 (Reuters) - California diesel prices climbed 52.5 cents a gallon this week in the San Francisco Bay market because of a hydrotreater outage at Chevron Corps (CVX.N) Richmond, Califo… [+1186 chars]'},
 {'source': {'id': 'reuters', 'name': 'Reuters'},
  'author': None,
  'title': 'Russian oil refiners signal deeper cuts to refinery runs amid overstocking - Reuters.com',
  'description': 'Major Russian oil refiners have told the Energy Ministry they expect to make deeper cuts to refinery runs in the coming weeks due to overstocking after a sharp drop in European buying, four sources familiar with the matter told Reuters.',
  'url': 'https://www.reuters.com/business/energy/russian-oil-refiners-signal-deeper-cuts-refinery-runs-amid-overstocking-2022-03-31/',
  'urlToImage': 'https://www.reuters.com/resizer/vQwJwTtH068hPYD7zi-Bhtu8cjI=/1200x628/smart/filters:quality(80)/cloudfront-us-east-2.images.arcpublishing.com/reuters/LWDNMKX3QFO45EMX7LVLX76ZXQ.jpg',
  'publishedAt': '2022-03-31T09:01:00Z',
  'content': 'March 31 (Reuters) - Major Russian oil refiners have told the Energy Ministry they expect to make deeper cuts to refinery runs in the coming weeks due to overstocking after a sharp drop in European b… [+2001 chars]'},
 {'source': {'id': None, 'name': 'The Guardian'},
  'author': 'Associated Press',
  'title': 'US federal alert warns of the discovery of malicious cyber tools',
  'description': 'Cybersecurity officials said the evidence suggests Russia is behind the tools – configured to target North American energy concernsMultiple US government agencies issued a joint alert Wednesday warning of the discovery of malicious cyber tools created by unna…',
  'url': 'https://amp.theguardian.com/us-news/2022/apr/13/us-alert-malicious-cyber-tools-russia',
  'urlToImage': 'https://i.guim.co.uk/img/media/55bba7b9da1201850e76bf892464bdba021cdd7d/0_267_4004_2402/master/4004.jpg?width=1200&height=630&quality=85&auto=format&fit=crop&overlay-align=bottom%2Cleft&overlay-width=100p&overlay-base64=L2ltZy9zdGF0aWMvb3ZlcmxheXMvdGctZGVmYXVsdC5wbmc&enable=upscale&s=f8aeebda1805bc0b471b0c28b46d1763',
  'publishedAt': '2022-04-14T01:12:58Z',
  'content': 'Multiple US government agencies issued a joint alert Wednesday warning of the discovery of malicious cyber tools created by unnamed advanced threat actors that they said were capable of gaining full … [+3943 chars]'},
 {'source': {'id': None, 'name': 'Yahoo Entertainment'},
  'author': 'Reuters',
  'title': 'California diesel, jet prices rise on Chevron hydrotreater outage -trade',
  'description': 'California diesel prices climbed 52.5 cents a gallon this week in the San Francisco Bay market because of a hydrotreater outage at Chevron Corp’s Richmond...',
  'url': 'https://news.yahoo.com/california-diesel-jet-prices-rise-222236608.html',
  'urlToImage': 'https://s.yimg.com/uu/api/res/1.2/.dw7_mjtoKl5s5gkohL1kQ--~B/aD00OTY7dz04MDA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/reuters.com/a2cda8a842d65211de3d07d6aa91d8ee',
  'publishedAt': '2022-03-25T22:22:36Z',
  'content': 'HOUSTON (Reuters) - California diesel prices climbed 52.5 cents a gallon this week in the San Francisco Bay market because of a hydrotreater outage at Chevron Corps Richmond, California, refinery, sa… [+995 chars]'},
 {'source': {'id': None, 'name': 'Seeking Alpha'},
  'author': 'Nathan Allen',
  'title': 'Suncor refinery fire could extend maintenance outage',
  'description': "Early Wednesday, a fire broke out at Suncor's (SU) Strathcona refinery in Edmonton, sending one person to the hospital.\xa0Monday, Suncor (SU) announced the refinery would be going...",
  'url': 'https://seekingalpha.com/news/3819004-suncor-refinery-fire-could-extend-maintenance-outage',
  'urlToImage': 'https://static.seekingalpha.com/cdn/s3/uploads/getty_images/1266019262/image_1266019262.jpg?io=getty-c-w750',
  'publishedAt': '2022-03-30T18:45:51Z',
  'content': 'THEGIFT777/E+ via Getty Images'},
 {'source': {'id': None, 'name': 'Yahoo Entertainment'},
  'author': 'Vance Cariaga',
  'title': 'Why Are Gas Prices Still So High in California?',
  'description': "Californians don't want to hear about how much you have to pay for gas if you're a non-resident. While the other 49 states pay an average of $4.236 a gallon,...",
  'url': 'https://finance.yahoo.com/news/why-gas-prices-still-high-161751889.html',
  'urlToImage': 'https://s.yimg.com/ny/api/res/1.2/vj0GxcbxEFWihJK0YhP.kg--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02NzU-/https://s.yimg.com/uu/api/res/1.2/CO66VexL7yr0nO6sOSLaFw--~B/aD0xMDgwO3c9MTkyMDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/gobankingrates_644/6f944c5924d1401a9dad99fa6d435fb9',
  'publishedAt': '2022-03-24T16:17:51Z',
  'content': 'Extreme Media / iStock.com\r\nCalifornians dont want to hear about how much you have to pay for gas if youre a non-resident. While the other 49 states pay an average of $4.236 a gallon, according to AA… [+2893 chars]'},
 {'source': {'id': None, 'name': 'AOL'},
  'author': 'LA Times',
  'title': "Los Angeles gas prices drop for 15th consecutive day following 'unprecedented rise'",
  'description': 'Prices are also inching down across California and the U.S., with the average American paying $4.098 for a regular gallon, down from $4.176 a week ago.',
  'url': 'https://www.aol.com/news/los-angeles-gas-prices-drop-180519112.html',
  'urlToImage': 'https://s.yimg.com/uu/api/res/1.2/E6VEMLGZNQ5nkA4wPvV7gw--~B/aD01NjA7dz04NDA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/aol_la_times_articles_830/c2b5cb7d385cb994de8316f0a16d4d56',
  'publishedAt': '2022-04-12T18:05:19Z',
  'content': 'Jorge Garcia fills up his tank at Costco in Azusa. (Robert Gauthier / Los Angeles Times)\r\nGas prices in the Los Angeles Metropolitan area on Tuesday dropped for the 15th consecutive day, with an aver… [+3852 chars]'},
 {'source': {'id': None, 'name': 'Yahoo Entertainment'},
  'author': 'Hayley Smith',
  'title': "Los Angeles gas prices drop for 15th consecutive day following 'unprecedented rise'",
  'description': 'Prices are also inching down across California and the U.S., with the average American paying $4.098 for a regular gallon, down from $4.176 a week ago.',
  'url': 'https://news.yahoo.com/los-angeles-gas-prices-drop-180519724.html',
  'urlToImage': 'https://s.yimg.com/uu/api/res/1.2/0BbytDtAxpIHJrxJ.6XGnQ--~B/aD01NjA7dz04NDA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/la_times_articles_853/6b17c7e86e7c4eaa1666eaa459711ed1',
  'publishedAt': '2022-04-12T18:05:19Z',
  'content': 'Jorge Garcia fills up his tank at Costco in Azusa. (Robert Gauthier / Los Angeles Times)\r\nGas prices in the Los Angeles Metropolitan area on Tuesday dropped for the 15th consecutive day, with an aver… [+3852 chars]'},
 {'source': {'id': None, 'name': 'HuffPost'},
  'author': 'Xander Peters',
  'title': "How Texas' Energy Woes Are Derailing Life In This Houston Neighborhood",
  'description': 'Residents of Houston’s diverse Southwest Crossing are getting an unwelcome new neighbor: a propane storage facility.',
  'url': 'https://www.huffpost.com/entry/houston-southwest-crossing-propane-energy_n_624b4179e4b0587dee6d45db',
  'urlToImage': 'https://img.huffingtonpost.com/asset/624c7c6223000053b413916a.jpeg?cache=ErSt3uPnTB&ops=1778_1000',
  'publishedAt': '2022-04-09T12:00:38Z',
  'content': "Texas has expanded storage for natural gas and propane, which backers say will shore up the state's energy grid.\r\nHOUSTON The Southwest Crossing subdivision has always been a quiet place, a haven jus… [+13896 chars]"},
 {'source': {'id': 'newsweek', 'name': 'Newsweek'},
  'author': 'Giulia Carbonaro',
  'title': 'Californians Flock to Mexico for Cheap Gas as Prices Rise to $6 in State',
  'description': "Gas prices have dropped across the U.S. in the last two weeks after reaching a record high. The same isn't true for California, where prices keep rising.",
  'url': 'https://www.newsweek.com/californians-mexico-cheap-gas-prices-rise-1691890',
  'urlToImage': 'https://d.newsweek.com/en/full/2008750/gas-station-us-stock.jpg',
  'publishedAt': '2022-03-25T16:28:29Z',
  'content': 'Californians are traveling to Mexico for cheaper gas, as fuel prices surged following the Russian invasion of Ukraine, according to The San Diego Union-Tribune and the Los Angeles Times.\r\nThe nationa… [+3941 chars]'},
 {'source': {'id': 'cbs-news', 'name': 'CBS News'},
  'author': 'Bill Whitaker',
  'title': 'U.S. officials preparing for potential Russian cyberattacks',
  'description': "Bill Whitaker reports on the proven capabilities of Russia's hackers, who just a few years ago were able to infiltrate the computer network of a Kansas nuclear power plant.",
  'url': 'https://www.cbsnews.com/news/russia-cyberattacks-60-minutes-2022-04-17/',
  'urlToImage': 'https://cbsnews2.cbsistatic.com/hub/i/r/2022/04/17/1f4ebece-0422-4433-b122-22e4d998c0e3/thumbnail/1200x630/79b659cde2b7460f2d8c1d7c53ee34e1/russianhackingarticle.jpg',
  'publishedAt': '2022-04-17T22:57:26Z',
  'content': 'This past week, the U.S. government issued an urgent warning about dangerous new malware that could cripple industrial systems worldwide. It comes on the heels of Ukraine withstanding an attempt by R… [+12825 chars]'},
 {'source': {'id': None, 'name': 'Gadgets360.com'},
  'author': 'Associated Press',
  'title': 'Malicious Cyber Tools to Sabotage Energy and Other Critical Industries Have Been Discovered: US Agencies',
  'description': 'Several malicious cyber tools that can damage energy sector and other critical industries have been discovered by multiple US government agencies. There is evidence that Russia maybe behind the creation of these tools.',
  'url': 'https://gadgets360.com/internet/news/malware-malicious-cyber-tools-russia-ndustrial-control-system-discovered-us-agencies-2888219',
  'urlToImage': 'https://i.gadgets360cdn.com/large/android_malware_sora_shimazaki_pexels_1649425870825.jpg',
  'publishedAt': '2022-04-14T11:09:40Z',
  'content': 'Multiple US government agencies issued a joint alert Wednesday warning of the discovery of a suite of malicious cyber tools created by unnamed advanced threat actors that are capable of sabotaging th… [+3977 chars]'},
 {'source': {'id': None, 'name': 'Tech Xplore'},
  'author': 'Frank Bajak',
  'title': 'US agencies: Industrial control system malware discovered',
  'description': 'Multiple U.S. government agencies issued a joint alert Wednesday warning of the discovery of a suite of malicious cyber tools created by unnamed advanced threat actors that are capable of sabotaging the energy sector and other critical industries.',
  'url': 'https://techxplore.com/news/2022-04-agencies-industrial-malware.html',
  'urlToImage': 'https://scx2.b-cdn.net/gfx/news/hires/2022/us-agencies-industrial.jpg',
  'publishedAt': '2022-04-14T08:26:51Z',
  'content': 'Multiple U.S. government agencies issued a joint alert Wednesday warning of the discovery of a suite of malicious cyber tools created by unnamed advanced threat actors that are capable of sabotaging … [+4561 chars]'},
 {'source': {'id': None, 'name': 'KPBS'},
  'author': 'https://www.kpbs.org/staff/city-news-service',
  'title': 'Average San Diego County gas price rises for 30th consecutive day',
  'description': 'The average price of a gallon of self-serve regular gasoline in San Diego County rose Thursday for the 30th consecutive day, increasing 1.3 cents to a record $5.981.',
  'url': 'https://www.kpbs.org/news/local/2022/03/24/average-san-diego-county-gas-price-rises-for-30th-consecutive-day',
  'urlToImage': 'https://cdn.kpbs.org/dims4/default/fb79140/2147483647/strip/true/crop/4032x2117+0+66/resize/1200x630!/quality/90/?url=http%3A%2F%2Fkpbs-brightspot.s3.amazonaws.com%2Fa3%2F0b%2Fbfc3f99346e494d2db39aee6d748%2Farco-gas-station-allied-gardens-1.jpg',
  'publishedAt': '2022-03-24T16:40:58Z',
  'content': 'The average price of a gallon of self-serve regular gasoline in San Diego County rose Thursday for the 30th consecutive day, increasing 1.3 cents to a record $5.981.\r\nThe average price has risen $1.2… [+1489 chars]'},
 {'source': {'id': None, 'name': 'KPBS'},
  'author': 'https://www.kpbs.org/staff/city-news-service',
  'title': 'Average San Diego County gas price rises for 24th consecutive day',
  'description': 'The average price of a gallon of self-serve regular gasoline in San Diego County rose Friday for the 24th consecutive day, increasing 1.9 cents to a record $5.839.',
  'url': 'https://www.kpbs.org/news/local/2022/03/18/average-san-diego-county-gas-price-rises-24th-consecutive-day',
  'urlToImage': 'https://cdn.kpbs.org/dims4/default/8a5f25f/2147483647/strip/true/crop/4032x2117+0+0/resize/1200x630!/quality/90/?url=http%3A%2F%2Fkpbs-brightspot.s3.amazonaws.com%2F04%2Fba%2Fd80e6aec4a60850af6ffa4bd3751%2Fgas-prices-san-diego-1.jpg',
  'publishedAt': '2022-03-18T19:00:35Z',
  'content': 'The average price of a gallon of self-serve regular gasoline in San Diego County rose Friday for the 24th consecutive day, increasing 1.9 cents to a record $5.839.\r\nThe average price has risen $1.095… [+643 chars]'},
 {'source': {'id': None, 'name': 'KPBS'},
  'author': 'https://www.kpbs.org/staff/city-news-service',
  'title': 'Average San Diego County gas price rises for 27th consecutive day',
  'description': 'The average price of a gallon of self-serve regular gasoline in San Diego County rose Monday for the 27th consecutive day, increasing 1.1 cents to a record $5.922, one day after rising 2.3 cents.',
  'url': 'https://www.kpbs.org/news/local/2022/03/21/average-san-diego-county-gas-price-rises-27th-consecutive-day',
  'urlToImage': 'https://cdn.kpbs.org/dims4/default/7671783/2147483647/strip/true/crop/4032x2117+0+454/resize/1200x630!/quality/90/?url=http%3A%2F%2Fkpbs-brightspot.s3.amazonaws.com%2Fcd%2Fcf%2Fe34a6e48421a9027b898f4f6c352%2Fgas-station-golden-hill-2.jpg',
  'publishedAt': '2022-03-21T19:52:31Z',
  'content': 'The average price of a gallon of self-serve regular gasoline in San Diego County rose Monday for the 27th consecutive day, increasing 1.1 cents to a record $5.922, one day after rising 2.3 cents.\r\nTh… [+804 chars]'},
 {'source': {'id': 'the-times-of-india', 'name': 'The Times of India'},
  'author': 'AFP',
  'title': 'Oil prices soar on Saudi, Russian supply fears',
  'description': 'Top producer Saudi Arabia warned that Yemeni rebel attacks on the kingdom\'s oil facilities pose a "direct threat" to global supplies, the comments helping Brent North Sea crude surge 6.1 percent to $114.55 per barrel with WTI rising 5.5 percent to $110.48.',
  'url': 'https://economictimes.indiatimes.com/news/international/business/oil-prices-soar-on-saudi-russian-supply-fears/articleshow/90358750.cms',
  'urlToImage': 'https://img.etimg.com/thumb/msid-90358758,width-1070,height-580,imgsize-19124,overlay-economictimes/photo.jpg',
  'publishedAt': '2022-03-21T14:32:08Z',
  'content': 'Oil prices soared Monday as a weekend attack on Saudi facilities and EU discussions on banning Russian crude raised concerns over global supplies.\r\nTop producer Saudi Arabia warned that Yemeni rebel … [+2882 chars]'},
 {'source': {'id': None, 'name': 'Los Angeles Times'},
  'author': 'Hayley Smith',
  'title': "Los Angeles gas prices drop for 15th consecutive day following 'unprecedented rise'",
  'description': 'Prices are also inching down across California and the U.S., with the average American paying $4.098 for a regular gallon, down from $4.176 a week ago.',
  'url': 'https://www.latimes.com/california/story/2022-04-12/los-angeles-gas-prices-drop-for-15th-consecutive-day-following-unprecedented-rise',
  'urlToImage': 'https://ca-times.brightspotcdn.com/dims4/default/63ab8f1/2147483647/strip/true/crop/3000x1575+0+213/resize/1200x630!/quality/90/?url=https%3A%2F%2Fcalifornia-times-brightspot.s3.amazonaws.com%2F5c%2F64%2F98b45cda4f21b09fe3c5cd1b9c67%2F934860-me-0322-gas-5-rcg.jpg',
  'publishedAt': '2022-04-12T18:05:19Z',
  'content': 'Gas prices in the Los Angeles Metropolitan area on Tuesday dropped for the 15th consecutive day, with an average gallon of regular gasoline decreasing 1.3 cents to $5.849, according to figures from t… [+3695 chars]'},
 {'source': {'id': None, 'name': 'Bangalorenewstoday.com'},
  'author': None,
  'title': 'The real story behind Russia-Ukraine cyber wars',
  'description': '“Russian president is likely to use cyber attacks as a form of retaliation against our country for its action to counter Russias incursion in Ukraine.” Mumbai',
  'url': 'https://bangalorenewstoday.com/top-news/the-real-story-behind-russia-ukraine-cyber-wars/',
  'urlToImage': 'https://static.toiimg.com/imagenext/toiblogs/photo/blogs/wp-content/uploads/2022/02/yashavi-yadav-blog.jpg',
  'publishedAt': '2022-04-05T12:41:00Z',
  'content': 'Russian president is likely to use cyber attacks as a form of retaliation against our country for its action to counter Russias incursion in Ukraine.\r\n President of USA, Joe Biden at Business Roundta… [+12427 chars]'},
 {'source': {'id': None, 'name': 'OilPrice.com'},
  'author': 'Alex Kimani',
  'title': 'Tight Oil Markets Are Sending Fuel Margins Through The Roof',
  'description': "The oil price rally has really cooled down over the past two weeks, with oil prices declining to levels last seen prior to Russia's invasion of Ukraine. Brent oil (CO1:COM) prices fell ~2% Thursday to trade below $100/b, while the price for a barrel of Brent …",
  'url': 'https://oilprice.com/Energy/Gas-Prices/Tight-Oil-Markets-Are-Sending-Fuel-Margins-Through-The-Roof.html',
  'urlToImage': 'https://d32r1sh890xpii.cloudfront.net/article/718x300/2022-04-08_acq59v362f.jpg',
  'publishedAt': '2022-04-08T23:00:00Z',
  'content': 'The U.S. benchmark natural gas…\r\nConsumers are becoming increasingly stressed…\r\nGovernments are looking to ease…\r\nBy Alex Kimani - Apr 08, 2022, 6:00 PM CDTThe oil price rally has really cooled down … [+5282 chars]'}]

In [143]:
# create sentiment score & store it in df:
text_sentiment = []

for article in refinery_headlines["articles"]:
    try:
        text = article["content"]
        date = article["publishedAt"]
        sentiment = analyzer.polarity_scores(text)
        compound = sentiment["compound"]
        pos = sentiment["pos"]
        neu = sentiment["neu"]
        neg = sentiment["neg"]
        
        text_sentiment.append({
            "text": text,
            "date": date,
            "compound": compound,
            "positive": pos,
            "negative": neg,
            "neutral": neu
            
        })
    except AttributeError:
        pass

In [144]:
# The sum of pos, neg, neu intensities give 1. 
# Compound ranges from -1 to 1 and is the metric used to draw the overall sentiment.
  # positive if compound >= 0.5
  # neutral if -0.5 < compound < 0.5
  # negative if -0.5 >= compound

sentiment

{'neg': 0.0, 'neu': 0.928, 'pos': 0.072, 'compound': 0.3612}

In [145]:
# Visualize results in a dataframe

df=pd.DataFrame(text_sentiment)
df

,text,date,compound,positive,negative,neutral
0,"HOUSTON, March 25 (Reuters) - California diese...",2022-03-25T22:22:00Z,0.0000,0.000,0.000,1.000
1,March 31 (Reuters) - Major Russian oil refiner...,2022-03-31T09:01:00Z,-0.2960,0.053,0.109,0.838
2,Multiple US government agencies issued a joint...,2022-04-14T01:12:58Z,0.5859,0.274,0.137,0.590
3,HOUSTON (Reuters) - California diesel prices c...,2022-03-25T22:22:36Z,0.0000,0.000,0.000,1.000
4,THEGIFT777/E+ via Getty Images,2022-03-30T18:45:51Z,0.0000,0.000,0.000,1.000
5,Extreme Media / iStock.com\r\nCalifornians don...,2022-03-24T16:17:51Z,-0.2551,0.000,0.109,0.891
6,Jorge Garcia fills up his tank at Costco in Az...,2022-04-12T18:05:19Z,0.0000,0.000,0.000,1.000
7,Jorge Garcia fills up his tank at Costco in Az...,2022-04-12T18:05:19Z,0.0000,0.000,0.000,1.000
8,Texas has expanded storage for natural gas and...,2022-04-09T12:00:38Z,0.5574,0.129,0.000,0.871
9,Californians are traveling to Mexico for cheap...,2022-03-25T16:28:29Z,0.0000,0.000,0.000,1.000
10,"This past week, the U.S. government issued an ...",2022-04-17T22:57:26Z,-0.5719,0.047,0.144,0.809
11,Multiple US government agencies issued a joint...,2022-04-14T11:09:40Z,0.2500,0.217,0.143,0.640
12,Multiple U.S. government agencies issued a joi...,2022-04-14T08:26:51Z,0.2500,0.222,0.146,0.631
13,The average price of a gallon of self-serve re...,2022-03-24T16:40:58Z,0.0000,0.000,0.000,1.000
14,The average price of a gallon of self-serve re...,2022-03-18T19:00:35Z,0.0000,0.000,0.000,1.000
15,The average price of a gallon of self-serve re...,2022-03-21T19:52:31Z,0.0000,0.000,0.000,1.000
16,Oil prices soared Monday as a weekend attack o...,2022-03-21T14:32:08Z,-0.8271,0.046,0.267,0.687
17,Gas prices in the Los Angeles Metropolitan are...,2022-04-12T18:05:19Z,0.0000,0.000,0.000,1.000
18,Russian president is likely to use cyber attac...,2022-04-05T12:41:00Z,-0.4404,0.000,0.081,0.919
19,The U.S. benchmark natural gas…\r\nConsumers a...,2022-04-08T23:00:00Z,0.3612,0.072,0.000,0.928

In [146]:
# sort the compound values by descending score

df.sort_values(by='compound', ascending=False).head(5)

,text,date,compound,positive,negative,neutral
2,Multiple US government agencies issued a joint...,2022-04-14T01:12:58Z,0.5859,0.274,0.137,0.590
8,Texas has expanded storage for natural gas and...,2022-04-09T12:00:38Z,0.5574,0.129,0.000,0.871
19,The U.S. benchmark natural gas…\r\nConsumers a...,2022-04-08T23:00:00Z,0.3612,0.072,0.000,0.928
11,Multiple US government agencies issued a joint...,2022-04-14T11:09:40Z,0.2500,0.217,0.143,0.640
12,Multiple U.S. government agencies issued a joi...,2022-04-14T08:26:51Z,0.2500,0.222,0.146,0.631

In [147]:
# sort the compound values by asscending score

df.sort_values(by='compound', ascending=True).head(5)

,text,date,compound,positive,negative,neutral
16,Oil prices soared Monday as a weekend attack o...,2022-03-21T14:32:08Z,-0.8271,0.046,0.267,0.687
10,"This past week, the U.S. government issued an ...",2022-04-17T22:57:26Z,-0.5719,0.047,0.144,0.809
18,Russian president is likely to use cyber attac...,2022-04-05T12:41:00Z,-0.4404,0.000,0.081,0.919
1,March 31 (Reuters) - Major Russian oil refiner...,2022-03-31T09:01:00Z,-0.2960,0.053,0.109,0.838
5,Extreme Media / iStock.com\r\nCalifornians don...,2022-03-24T16:17:51Z,-0.2551,0.000,0.109,0.891

In [148]:
# describe overall sentiment of dataframe:

df.describe()

        compound   positive   negative    neutral
count  20.000000  20.000000  20.000000  20.000000
mean   -0.019300   0.053000   0.056800   0.890200
std     0.344872   0.087126   0.078926   0.143948
min    -0.827100   0.000000   0.000000   0.590000
25%    -0.063775   0.000000   0.000000   0.830750
50%     0.000000   0.000000   0.000000   0.964000
75%     0.062500   0.057750   0.116000   1.000000
max     0.585900   0.274000   0.267000   1.000000

In [55]:
from pynytimes import NYTAPI

ModuleNotFoundError: No module named 'pynytimes'

In [ ]:
nyt = NYTAPI("AGTGevw2BdpxCUBRjEyFC0ymAVDHVA0e", https=False)

In [ ]:
top_stories = nyt.top_stories(section='science')

In [ ]:
top_stories

In [ ]:
import datetime

articles = nyt.article_search(
    query = "Covid19",
    results = 10,
    dates = {
        "begin": datetime.datetime(2020, 3, 1),
        "end": datetime.datetime(2020, 10, 12)
    },
    options = {
        "sort": "oldest",
        "sources": [
            "New York Times",
            "AP",
            "Reuters",
            "International Herald Tribune"
        ],
        "news_desk": [
            "Politics"
        ],
        "type_of_material": [
            "News Analysis"
        ]
    }
)

In [ ]:
import pandas as pd
from nytimesarticle import articleAPI

In [ ]:
nyt_api_key='AGTGevw2BdpxCUBRjEyFC0ymAVDHVA0e'
api=articleAPI(nyt_api_key)
api

In [ ]:
import os
import json
import time
import requests
import datetime
import dateutil
import pandas as pd
from dateutil.relativedelta import relativedelta

In [12]:
end = datetime.date.today()
start = end - relativedelta(months=7)

NameError: name 'datetime' is not defined

In [ ]:
months_in_range = [x.split(' ') for x in pd.date_range(start, end, freq='MS').strftime("%Y %-m").tolist()]

In [ ]:
def send_request(date):
    '''Sends a request to the NYT Archive API for given date.'''
    base_url = 'https://api.nytimes.com/svc/archive/v1/'
    url = base_url + '/' + date[0] + '/' + date[1] + '.json?api-key=' + 'AGTGevw2BdpxCUBRjEyFC0ymAVDHVA0e'
    response = requests.get(url).json()
    time.sleep(6)
    return response


def is_valid(article, date):
    '''An article is only worth checking if it is in range, and has a headline.'''
    is_in_range = date > start and date < end
    has_headline = type(article['headline']) == dict and 'main' in article['headline'].keys()
    return is_in_range and has_headline


def parse_response(response):
    '''Parses and returns response as pandas data frame.'''
    data = {'headline': [],  
        'date': [], 
        'doc_type': [],
        'material_type': [],
        'section': [],
        'keywords': []}
    
    articles = response['response']['docs'] 
    for article in articles: # For each article, make sure it falls within our date range
        date = dateutil.parser.parse(article['pub_date']).date()
        if is_valid(article, date):
            data['date'].append(date)
            data['headline'].append(article['headline']['main']) 
            if 'section' in article:
                data['section'].append(article['section_name'])
            else:
                data['section'].append(None)
            data['doc_type'].append(article['document_type'])
            if 'type_of_material' in article: 
                data['material_type'].append(article['type_of_material'])
            else:
                data['material_type'].append(None)
            keywords = [keyword['value'] for keyword in article['keywords'] if keyword['name'] == 'subject']
            data['keywords'].append(keywords)
    return pd.DataFrame(data) 


def get_data(dates):
    '''Sends and parses request/response to/from NYT Archive API for given dates.'''
    total = 0
    print('Date range: ' + str(dates[0]) + ' to ' + str(dates[-1]))
    if not os.path.exists('headlines'):
        os.mkdir('headlines')
    for date in dates:
        response = send_request(date)
        df = parse_response(response)
        total += len(df)
        df.to_csv('headlines/' + date[0] + '-' + date[1] + '.csv', index=False)
        print('Saving headlines/' + date[0] + '-' + date[1] + '.csv...')
    print('Number of articles collected: ' + str(total))

In [ ]:
get_data(months_in_range)

In [13]:
response

NameError: name 'response' is not defined